# Use root/example as user/password credentials
version: '3.1'

services:

  chatdb:
    image: mariadb
    restart: always
    container_name: chat-mysql
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - chatdb-volume:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  chatdb-volume: